# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 18:51
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('Edad', models.IntegerField()),
                ('Raza', models.CharField(choices=[('Chihuahua', 'Chihuahua'), ('Poodle', 'Poodle'), ('Labrador', 'Labrador'), ('Pitbull', 'Pitbull'), ('Pastor Aleman', 'Pastor Aleman'), ('Husky', 'Husky'), ('Otro', 'Otro')], max_length=48)),
                ('Estado', models.CharField(choices=[('Adoptado', 'Adoptado'), ('Encontrado', 'Encontrado'), ('Se Busca', 'Se Busca'), ('Encontrado', 'Encontrado')], max_length=48)),
                ('Informacion', models.TextField()),
                ('Descripcion', models.TextField()),
                ('Foto', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('update', models.DateTimeField(auto_now=True)),
                ('marcadetiempo', models.DateTimeField(auto_now_add=True)),
                ('Autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Edad', models.IntegerField()),
                ('Telefono', models.IntegerField()),
                ('Email', models.CharField(default='correo@servicio.com', max_length=48)),
                ('Direccion', models.TextField()),
                ('Descripcion', models.TextField()),
                ('Foto', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
